In [1]:
import numpy as np

# Task 1: Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays.

In [63]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Intersect1d returns unique elements which matches in both 1d arrays.
np.intersect1d(a, b) 

array([2, 4])

# Task 2: Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

In [64]:
# Creating a range of values anf reshaping it into 2d matrix.
arr = np.arange(1,16).reshape(5,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


# Task 3: Convert Task 2 array to unidimensional array.

In [65]:
print(arr.flatten()) # Method 1: Flatten takes any dimensional array and changes it to unidimensional array.
np.reshape(arr, 15) # Method 2: Reshapes the array to 15 elements array.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Task 4: Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [75]:
# Each 5 array will contain 1 array which will contain 3 elements. 
arr3d = np.reshape(arr, (5,1,3)) 
arr3d

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]]])

# Task 5: Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [67]:
arr2d = np.reshape(arr3d, (5, 3))
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Task 6: Write a Python/Numpy code block that removes from array a any items that are also present in array b.

- np.delete uses indices to delete items from an ndarray
- np.intersect1d is returning 3 things.
    - 1) List of common elements.
    - 2) list of the indexes of the common elements in array a.
    - 3) List of the indexes of the common elements in array b.

In [68]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
np.delete(a, np.intersect1d(a, b, return_indices=True)[1])

array([ 7, 15,  1,  8])

# Task 7: Reading and extracting information from a text file using Numpy.

In [69]:
from pandas import read_csv
np.set_printoptions(suppress = True)
nyc_water = read_csv("https://raw.githubusercontent.com/AliHaider20/AIM-5001/main/Module6_Data.csv").to_numpy()
print(type(nyc_water))
nyc_water[:5]

<class 'numpy.ndarray'>


array([[   1979., 7102100.,    1512.,     213.],
       [   1980., 7071639.,    1506.,     213.],
       [   1981., 7089241.,    1309.,     185.],
       [   1982., 7109105.,    1382.,     194.],
       [   1983., 7181224.,    1424.,     198.]])

In [70]:
print("Maximum NYC Consumption(Million gallons per day) :", nyc_water[:, 2].max())

Maximum NYC Consumption(Million gallons per day) : 1512.0


In [71]:
print("Number of calendar years present are: ", nyc_water.shape[0]) # Method 1
print("Number of calendar years present are: ", len(np.unique(nyc_water[:,0]))) # Method 2 

Number of calendar years present are:  39
Number of calendar years present are:  39


In [72]:
print(f"For Per Capita(Gallons per person per day) mean is {nyc_water[:,-1].mean()} and STD is {nyc_water[:,-1].std()}")

For Per Capita(Gallons per person per day) mean is 160.30769230769232 and STD is 31.51894330370624


In [76]:
pop_diff = np.diff(nyc_water[:,1]) # Method 1: Taking the difference between consecutive elements.
pop_diff = np.ediff1d(nyc_water[:,1]) # Method 2
print("Population Differences: ", pop_diff)

Population Differences:  [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
